# Renders the authoritative zone file served by Knot (modules/containers/knot-auth.nix).
#
# Built from the SAME data blocky consumes — dns.nix (service records, CNAMEs)
# and lan-hosts.nix (physical hosts) — so there is one source of truth for what
# names point where. Do not add records here; add them to dns.nix / lan-hosts.nix
# and they appear in both places automatically.
#
# The zone file lands in the Nix store and is never written back to (Knot's
# zonefile-sync = -1), so it stays reproducible and reviewable in git.
{ lib, domain, serial }:

let
  dns = import ./dns.nix { inherit lib; };
  inherit (import ./lan-hosts.nix) lanHosts;

  mkA = name: ip: "${name}\tIN\tA\t${ip}";
  mkAAAA = name: ip: "${name}\tIN\tAAAA\t${ip}";

  # Physical hosts: single nullable ipv4/ipv6 per host.
  hostLines = lib.concatMap (h:
    (lib.optional (h.ipv4 != null) (mkA h.hostname h.ipv4))
    ++ (lib.optional (h.ipv6 != null) (mkAAAA h.hostname h.ipv6))
  ) lanHosts;

  # Service records: list-valued v4/v6 (k3s-api is an HA round-robin).
  recordLines = lib.concatLists (lib.mapAttrsToList (name: r:
    (map (mkA name) r.v4) ++ (map (mkAAAA name) r.v6)
  ) dns.records);

  cnameLines = lib.mapAttrsToList
    (name: target: "${name}\tIN\tCNAME\t${target}")
    dns.cnames;

in ''
  ; Generated by modules/networking/zone.nix -- do not edit by hand.
  ; Source data: modules/networking/dns.nix, modules/networking/lan-hosts.nix
  $ORIGIN ${domain}.
  $TTL 300

  @	IN	SOA	ns1.${domain}. hostmaster.${domain}. (
  		${toString serial}	; serial (flake lastModified)
  		3600		; refresh
  		900		; retry
  		604800		; expire
  		300 )		; negative TTL

  ; Apex nameserver. ns1 is the public IPv4 front door (router DNAT -> dnsdist),
  ; not this container's LAN address -- see modules/containers/public-dns-proxy.nix.
  @	IN	NS	ns1.${domain}.
  ns1	IN	A	64.186.8.205

  ; Delegation to k8s_gateway, which auto-discovers LoadBalancer Services.
  ; The NS target is in-zone (no glue needed -- resolvers already hold ns1's A
  ; from above), so v4-only resolvers reach the subzone at the same public IPv4;
  ; the cluster's own :53 is never exposed. LAN clients reach this subzone via
  ; kresd's forward stub instead (modules/router/knot-resolver.nix), which
  ; follows the referral directly.
  k8s	IN	NS	ns1.${domain}.

  ; --- physical hosts (lan-hosts.nix) ---
  ${lib.concatStringsSep "\n" hostLines}

  ; --- service records (dns.nix) ---
  ${lib.concatStringsSep "\n" recordLines}

  ; --- aliases (dns.nix) ---
  ${lib.concatStringsSep "\n" cnameLines}
''
